### ISSUE TITLE
Error: Cannot uglify file

### ISSUE THREAD

**Issue by bostrt** [dantetam/dantequest#1]
Running `build.sh` and uglify cannot process three files:

```
Error: Cannot uglify file: /home/test/code/dantequest/client-build/js/app.js. Skipping it. Error is:
Unexpected token operator, expected punc (line: 518, col: 52, pos: 18514)
...
Error: Cannot uglify file: /home/test/code/dantequest/client-build/js/conversation.js. Skipping it. Error is:
Unexpected token operator, expected punc (line: 65, col: 43, pos: 2542)
...
Error: Cannot uglify file: /home/test/code/dantequest/client-build/js/game.js. Skipping it. Error is:
Unexpected token operator, expected punc (line: 3734, col: 43, pos: 143610)
```

Maps to the following lines:

https://github.com/dantetam/dantequest/blob/master/client/js/app.js#L533
https://github.com/dantetam/dantequest/blob/master/client/js/conversation.js#L65

**Comment by dantetam** [comment]
Hello, nice of you to work with my experimental BrowserQuest node/socket.io fork, appears the error is using default parameters with JS functions, which is an ES6 feature.
